name: react

permissions:
  contents: write

on: push

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: 读取仓库内容
          uses: actions/checkout@v4

        # - name: 部署
        #   uses: JamesIves/github-pages-deploy-action@v4
        #   with: 
        #     branch: gh-page
        #     folder: build
        
        - name: 登录Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{secrets.DOCKER_HUB_USERNAME}}
            password: ${{secrets.DOCKER_HUB_PASSWORD}}

        - name: 构建并推送到Docker Hub
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: wrgfhgv/react-app:latest
          
  